# Jekyll config

# Site settings
title: Co-op Health Station
description: Co-op Health Station Prototyping
baseurl: ""
url: "http://coop-health-station.heroku.com"

# Build settings
source: ./
destination: ../build
keep_files: ['css', 'js', 'assets']
markdown: kramdown
